<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Media extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'post_id',
        'filename',
        'original_filename',
        'path',
        'url',
        'mime_type',
        'size',
        'width',
        'height',
        'alt_text',
        'caption',
    ];

    protected $casts = [
        'width' => 'integer',
        'height' => 'integer',
        'size' => 'integer',
    ];

    /**
     * Get the user that owns the media.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the post that owns the media.
     */
    public function post(): BelongsTo
    {
        return $this->belongsTo(Post::class);
    }

    /**
     * Get the tags for the media.
     */
    public function tags(): HasMany
    {
        return $this->hasMany(MediaTag::class);
    }

    /**
     * Get auto-generated tags.
     */
    public function autoGeneratedTags(): HasMany
    {
        return $this->hasMany(MediaTag::class)->where('is_auto_generated', true);
    }

    /**
     * Get manually added tags.
     */
    public function manualTags(): HasMany
    {
        return $this->hasMany(MediaTag::class)->where('is_auto_generated', false);
    }

    /**
     * Check if media is an image.
     */
    public function isImage(): bool
    {
        return str_starts_with($this->mime_type, 'image/');
    }

    /**
     * Get formatted file size.
     */
    public function getFormattedSizeAttribute(): string
    {
        $bytes = $this->size;
        $units = ['B', 'KB', 'MB', 'GB'];

        for ($i = 0; $bytes > 1024 && $i < count($units) - 1; $i++) {
            $bytes /= 1024;
        }

        return round($bytes, 2) . ' ' . $units[$i];
    }

    /**
     * Get the URL for the media.
     */
    public function getUrlAttribute(): string
    {
        return $this->attributes['url'] ?? url($this->path);
    }
}