<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class MediaTag extends Model
{
    use HasFactory;

    protected $fillable = [
        'media_id',
        'tag',
        'confidence',
        'is_auto_generated',
        'source_model',
    ];

    protected $casts = [
        'confidence' => 'float',
        'is_auto_generated' => 'boolean',
    ];

    /**
     * Get the media that owns the tag.
     */
    public function media(): BelongsTo
    {
        return $this->belongsTo(Media::class);
    }

    /**
     * Scope a query to only include auto-generated tags.
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope a query to only include manually added tags.
     */
    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }

    /**
     * Scope a query to get tags with confidence above threshold.
     */
    public function scopeConfidenceAbove($query, float $threshold = 0.5)
    {
        return $query->where('confidence', '>=', $threshold);
    }
}