version: '3.8'

services:
  # MySQL Database - Production Configuration
  mysql:
    image: mysql:8.0
    secrets:
      - mysql_root_password
      - mysql_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-blogml}
      MYSQL_USER: ${DB_USERNAME:-blogml_user}
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD__FILE: /run/secrets/mysql_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - blogml-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 30s
      retries: 3
      start_period: 60s

  # Redis Cache - Production Configuration
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - blogml-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    command: redis-server --appendonly yes --maxmemory 400mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s

  # Backend API (Laravel) - Production Configuration
  backend:
    image: blogml/backend:latest
    secrets:
      - app_key
      - db_password
      - mail_password
    environment:
      APP_NAME: ${APP_NAME:-BlogML}
      APP_ENV: ${APP_ENV:-production}
      APP_KEY__FILE: /run/secrets/app_key
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-https://blogml.local}
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      LOG_LEVEL: ${LOG_LEVEL:-error}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-blogml}
      DB_USERNAME: ${DB_USERNAME:-blogml_user}
      DB_PASSWORD__FILE: /run/secrets/db_password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MEMCACHED_HOST: 127.0.0.1:11211
      ML_SERVICE_URL: http://ml-service:8000
      MAIL_MAILER: ${MAIL_MAILER:-smtp}
      MAIL_HOST: ${MAIL_HOST:-smtp.mailtrap.io}
      MAIL_PORT: ${MAIL_PORT:-2525}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD__FILE: /run/secrets/mail_password
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-tls}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${APP_NAME}
    volumes:
      - backend_storage:/var/www/html/storage
      - backend_logs:/var/www/html/storage/logs
    networks:
      - blogml-network
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        order: start-first
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      timeout: 30s
      interval: 30s
      retries: 3
      start_period: 60s

  # ML Service (Python FastAPI) - Production Configuration
  ml-service:
    image: blogml/ml-service:latest
    secrets:
      - hf_token
    environment:
      HF_TOKEN__FILE: /run/secrets/hf_token
      REDIS_URL: redis://redis:6379
      BACKEND_URL: http://backend:9000
      LOG_LEVEL: ${ML_LOG_LEVEL:-INFO}
      MODEL_CACHE_DIR: /app/models
      MAX_WORKERS: 4
    volumes:
      - ml_models:/app/models
      - ml_logs:/app/logs
    networks:
      - blogml-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: rollback
        order: start-first
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 30s
      interval: 30s
      retries: 3
      start_period: 120s

  # Frontend (Vue.js) - Production Configuration
  frontend:
    image: blogml/frontend:latest
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://blogml.local/api}
      VITE_ML_SERVICE_URL: ${VITE_ML_SERVICE_URL:-https://blogml.local/ml}
    networks:
      - blogml-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 20s
        failure_action: rollback
        order: start-first
    depends_on:
      - backend
      - ml-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s

  # Nginx Reverse Proxy - Production Configuration
  nginx:
    image: nginx:alpine
    secrets:
      - ssl_cert
      - ssl_key
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
      - nginx_cache:/var/cache/nginx
    networks:
      - blogml-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    depends_on:
      - frontend
      - backend
      - ml-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s

# Secrets for production
secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true
  app_key:
    external: true
  db_password:
    external: true
  mail_password:
    external: true
  hf_token:
    external: true
  ssl_cert:
    external: true
  ssl_key:
    external: true

# Persistent volumes
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/blogml/data/mysql
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/blogml/data/redis
  backend_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/blogml/data/backend/storage
  backend_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/blogml/logs/backend
  ml_models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/blogml/data/ml-models
  ml_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/blogml/logs/ml-service
  nginx_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/blogml/logs/nginx
  nginx_cache:
    driver: local

# Networks
networks:
  blogml-network:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16