version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-blogml}
      MYSQL_USER: ${DB_USERNAME:-blogml_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-blogml_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - blogml-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 30s
      retries: 3
      start_period: 60s

  # Redis Cache
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - blogml-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s

  # Backend API (Laravel)
  backend:
    image: blogml/backend:latest
    environment:
      APP_NAME: ${APP_NAME:-BlogML}
      APP_ENV: ${APP_ENV:-local}
      APP_KEY: ${APP_KEY:-base64:EWsyRMLy784gJZfY8RqX9tWcA6ZI9rsue4e2X}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:9000}
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      LOG_LEVEL: ${LOG_LEVEL:-error}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-blogml}
      DB_USERNAME: ${DB_USERNAME:-blogml_user}
      DB_PASSWORD: ${DB_PASSWORD:-blogml_password}
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MEMCACHED_HOST: 127.0.0.1:11211
      ML_SERVICE_URL: http://ml-service:8000
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: "${APP_NAME}"
    volumes:
      - backend_storage:/var/www/html/storage
      - backend_logs:/var/www/html/storage/logs
    networks:
      - blogml-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        order: start-first
  
  # ML Service (Python FastAPI)
  ml-service:
    image: blogml/ml-service:latest
    environment:
      HF_TOKEN: ${HF_TOKEN}
      HUGGINGFACE_API_TOKEN: ${HUGGINGFACE_API_TOKEN}
      REDIS_URL: redis://redis:6379
      BACKEND_URL: http://backend:9000
      LOG_LEVEL: ${ML_LOG_LEVEL:-INFO}
      MODEL_CACHE_DIR: /app/models
      MAX_WORKERS: 2
    volumes:
      - ml_models:/app/models
      - ml_logs:/app/logs
    networks:
      - blogml-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 60s
        failure_action: rollback
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 30s
      interval: 30s
      retries: 3
      start_period: 120s

  # Frontend (Vue.js)
  frontend:
    image: blogml/frontend:latest
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost/api}
      VITE_ML_SERVICE_URL: ${VITE_ML_SERVICE_URL:-http://localhost/ml}
    networks:
      - blogml-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 20s
        failure_action: rollback
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
      - nginx_cache:/var/cache/nginx
      - ./nginx/wait-for-services.sh:/wait-for-services.sh:ro
    networks:
      - blogml-network
    command: /bin/sh -c "chmod +x /wait-for-services.sh && /wait-for-services.sh && nginx -g 'daemon off;'"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s

# Persistent volumes
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  backend_storage:
    driver: local
  backend_logs:
    driver: local
  ml_models:
    driver: local
  ml_logs:
    driver: local
  nginx_logs:
    driver: local
  nginx_cache:
    driver: local

# Networks
networks:
  blogml-network:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16